export const defaultProject = {
  id: 'demo-project',
  name: 'Funil de aquisição',
  graph: {
    nodes: [
      {
        id: 'traffic-1',
        type: 'funnel',
        position: { x: 40, y: 170 },
        data: {
          label: 'Meta Ads',
          kind: 'traffic',
          conversionRate: 100,
          visitors: 3500,
          monthlyBudget: 4725,
          acquisitionModel: 'cpc',
          sourceType: 'other',
          cpc: 1.35,
          cpm: 22,
          ctr: 1.5,
          price: 0,
          productCost: 0,
          refundRate: 0,
        },
      },
      {
        id: 'optin-1',
        type: 'funnel',
        position: { x: 310, y: 170 },
        data: {
          label: 'Isca digital',
          kind: 'optin',
          conversionRate: 38,
          visitors: 0,
          cpc: 0,
          price: 0,
          productCost: 0,
          refundRate: 0,
        },
      },
      {
        id: 'sales-1',
        type: 'funnel',
        position: { x: 580, y: 170 },
        data: {
          label: 'Oferta principal',
          kind: 'sales',
          conversionRate: 16,
          visitors: 0,
          cpc: 0,
          price: 0,
          productCost: 0,
          refundRate: 0,
        },
      },
      {
        id: 'checkout-1',
        type: 'funnel',
        position: { x: 850, y: 170 },
        data: {
          label: 'Checkout',
          kind: 'checkout',
          conversionRate: 52,
          visitors: 0,
          cpc: 0,
          price: 497,
          productCost: 42,
          refundRate: 5,
        },
      },
      {
        id: 'upsell-1',
        type: 'funnel',
        position: { x: 1120, y: 70 },
        data: {
          label: 'Aceleração',
          kind: 'upsell',
          conversionRate: 24,
          visitors: 0,
          cpc: 0,
          price: 197,
          productCost: 12,
          refundRate: 3,
        },
      },
      {
        id: 'downsell-1',
        type: 'funnel',
        position: { x: 1120, y: 330 },
        data: {
          label: 'Plano essencial',
          kind: 'downsell',
          conversionRate: 19,
          visitors: 0,
          cpc: 0,
          price: 97,
          productCost: 5,
          refundRate: 3,
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'traffic-1',
        sourceHandle: 'yes',
        target: 'optin-1',
        type: 'smoothstep',
        data: { path: 'yes' },
      },
      {
        id: 'e2',
        source: 'optin-1',
        sourceHandle: 'yes',
        target: 'sales-1',
        type: 'smoothstep',
        data: { path: 'yes' },
      },
      {
        id: 'e3',
        source: 'sales-1',
        sourceHandle: 'yes',
        target: 'checkout-1',
        type: 'smoothstep',
        data: { path: 'yes' },
      },
      {
        id: 'e4',
        source: 'checkout-1',
        sourceHandle: 'yes',
        target: 'upsell-1',
        type: 'smoothstep',
        data: { path: 'yes' },
      },
      {
        id: 'e5',
        source: 'checkout-1',
        sourceHandle: 'no',
        target: 'downsell-1',
        type: 'smoothstep',
        data: { path: 'no' },
      },
    ],
  },
};
